apiVersion: v1
kind: ConfigMap
metadata:
  name: content
  namespace: {{ include "common.names.namespace" . | quote }}
data:
  index.html: |
    <html>
        <head>
            <title>ArgoCDaaS</title>
        </head>
        <body>
            <h1>Try it yourself!</h1>
            <img src="https://github.com/hs-martinbg/dcomdemo/blob/main/ArgoCDQR.png">
        </body>
    </html>